// <auto-generated />
namespace Vehicle_Insurance_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customers2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customers2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108130552289_Customers2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
